[package]
name = "epoch-cli"
version = "0.1.3"
authors = ["Anthony Christe <achriste@redvoxsound.com>"]
edition = "2018"
description = "A small command line utility for working with epoch timestamps."
repository = "https://bitbucket.org/redvoxhi/epoch-cli/src/master/"
license = "MIT"
keywords = ["epoch", "timestamp", "cli", "conversion"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
path = "src/main.rs"
name = "epoch"

[dependencies]
chrono = "0.4"
clap = {version = "2.33", features=["yaml"]}
